# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navreport.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='navreport.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnavreport.proto\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\xfc\x01\n\x10NavigationReport\x12\"\n\x01x\x18\x01 \x02(\x01\x42\x17\xa2?\x14 \x01)\x00\x00\x00\x00\x00\x88\xc3\xc0\x31\x00\x00\x00\x00\x00\x88\xc3@\x12\"\n\x01y\x18\x02 \x02(\x01\x42\x17\xa2?\x14 \x01)\x00\x00\x00\x00\x00\x88\xc3\xc0\x31\x00\x00\x00\x00\x00\x88\xc3@\x12\"\n\x01z\x18\x03 \x02(\x01\x42\x17\xa2?\x14 \x00)\x00\x00\x00\x00\x00\x88\xb3\xc0\x31\x00\x00\x00\x00\x00\x00\x00\x00\x12\x31\n\tveh_class\x18\x04 \x01(\x0e\x32\x1e.NavigationReport.VehicleClass\x12\x12\n\nbattery_ok\x18\x05 \x01(\x08\"*\n\x0cVehicleClass\x12\x07\n\x03\x41UV\x10\x01\x12\x07\n\x03USV\x10\x02\x12\x08\n\x04SHIP\x10\x03:\t\xa2?\x06\x08|\x10 (\x04'
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,])



_NAVIGATIONREPORT_VEHICLECLASS = _descriptor.EnumDescriptor(
  name='VehicleClass',
  full_name='NavigationReport.VehicleClass',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUV', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USV', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=249,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_NAVIGATIONREPORT_VEHICLECLASS)


_NAVIGATIONREPORT = _descriptor.Descriptor(
  name='NavigationReport',
  full_name='NavigationReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='NavigationReport.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\242?\024 \001)\000\000\000\000\000\210\303\3001\000\000\000\000\000\210\303@', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='NavigationReport.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\242?\024 \001)\000\000\000\000\000\210\303\3001\000\000\000\000\000\210\303@', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='NavigationReport.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\242?\024 \000)\000\000\000\000\000\210\263\3001\000\000\000\000\000\000\000\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='veh_class', full_name='NavigationReport.veh_class', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_ok', full_name='NavigationReport.battery_ok', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NAVIGATIONREPORT_VEHICLECLASS,
  ],
  serialized_options=b'\242?\006\010|\020 (\004',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=302,
)

_NAVIGATIONREPORT.fields_by_name['veh_class'].enum_type = _NAVIGATIONREPORT_VEHICLECLASS
_NAVIGATIONREPORT_VEHICLECLASS.containing_type = _NAVIGATIONREPORT
DESCRIPTOR.message_types_by_name['NavigationReport'] = _NAVIGATIONREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavigationReport = _reflection.GeneratedProtocolMessageType('NavigationReport', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONREPORT,
  '__module__' : 'navreport_pb2'
  # @@protoc_insertion_point(class_scope:NavigationReport)
  })
_sym_db.RegisterMessage(NavigationReport)


_NAVIGATIONREPORT.fields_by_name['x']._options = None
_NAVIGATIONREPORT.fields_by_name['y']._options = None
_NAVIGATIONREPORT.fields_by_name['z']._options = None
_NAVIGATIONREPORT._options = None
# @@protoc_insertion_point(module_scope)
