# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_navreport.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf_navreport.proto',
  package='underwater',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protobuf_navreport.proto\x12\nunderwater\"\xa9\x01\n\x0cStatusReport\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x38\n\tveh_class\x18\x04 \x01(\x0e\x32%.underwater.StatusReport.VehicleClass\x12\x12\n\nbattery_ok\x18\x05 \x01(\x08\"*\n\x0cVehicleClass\x12\x07\n\x03\x41UV\x10\x00\x12\x07\n\x03USV\x10\x01\x12\x08\n\x04SHIP\x10\x02\x62\x06proto3'
)



_STATUSREPORT_VEHICLECLASS = _descriptor.EnumDescriptor(
  name='VehicleClass',
  full_name='underwater.StatusReport.VehicleClass',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUV', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USV', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=168,
  serialized_end=210,
)
_sym_db.RegisterEnumDescriptor(_STATUSREPORT_VEHICLECLASS)


_STATUSREPORT = _descriptor.Descriptor(
  name='StatusReport',
  full_name='underwater.StatusReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='underwater.StatusReport.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='underwater.StatusReport.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='underwater.StatusReport.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='veh_class', full_name='underwater.StatusReport.veh_class', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_ok', full_name='underwater.StatusReport.battery_ok', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSREPORT_VEHICLECLASS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=210,
)

_STATUSREPORT.fields_by_name['veh_class'].enum_type = _STATUSREPORT_VEHICLECLASS
_STATUSREPORT_VEHICLECLASS.containing_type = _STATUSREPORT
DESCRIPTOR.message_types_by_name['StatusReport'] = _STATUSREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusReport = _reflection.GeneratedProtocolMessageType('StatusReport', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREPORT,
  '__module__' : 'protobuf_navreport_pb2'
  # @@protoc_insertion_point(class_scope:underwater.StatusReport)
  })
_sym_db.RegisterMessage(StatusReport)


# @@protoc_insertion_point(module_scope)
