# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navreport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnavreport.proto\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\xfc\x01\n\x10NavigationReport\x12\"\n\x01x\x18\x01 \x02(\x01\x42\x17\xa2?\x14 \x01)\x00\x00\x00\x00\x00\x88\xc3\xc0\x31\x00\x00\x00\x00\x00\x88\xc3@\x12\"\n\x01y\x18\x02 \x02(\x01\x42\x17\xa2?\x14 \x01)\x00\x00\x00\x00\x00\x88\xc3\xc0\x31\x00\x00\x00\x00\x00\x88\xc3@\x12\"\n\x01z\x18\x03 \x02(\x01\x42\x17\xa2?\x14 \x00)\x00\x00\x00\x00\x00\x88\xb3\xc0\x31\x00\x00\x00\x00\x00\x00\x00\x00\x12\x31\n\tveh_class\x18\x04 \x01(\x0e\x32\x1e.NavigationReport.VehicleClass\x12\x12\n\nbattery_ok\x18\x05 \x01(\x08\"*\n\x0cVehicleClass\x12\x07\n\x03\x41UV\x10\x01\x12\x07\n\x03USV\x10\x02\x12\x08\n\x04SHIP\x10\x03:\t\xa2?\x06\x08|\x10 (\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navreport_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _NAVIGATIONREPORT.fields_by_name['x']._options = None
  _NAVIGATIONREPORT.fields_by_name['x']._serialized_options = b'\242?\024 \001)\000\000\000\000\000\210\303\3001\000\000\000\000\000\210\303@'
  _NAVIGATIONREPORT.fields_by_name['y']._options = None
  _NAVIGATIONREPORT.fields_by_name['y']._serialized_options = b'\242?\024 \001)\000\000\000\000\000\210\303\3001\000\000\000\000\000\210\303@'
  _NAVIGATIONREPORT.fields_by_name['z']._options = None
  _NAVIGATIONREPORT.fields_by_name['z']._serialized_options = b'\242?\024 \000)\000\000\000\000\000\210\263\3001\000\000\000\000\000\000\000\000'
  _NAVIGATIONREPORT._options = None
  _NAVIGATIONREPORT._serialized_options = b'\242?\006\010|\020 (\004'
  _globals['_NAVIGATIONREPORT']._serialized_start=50
  _globals['_NAVIGATIONREPORT']._serialized_end=302
  _globals['_NAVIGATIONREPORT_VEHICLECLASS']._serialized_start=249
  _globals['_NAVIGATIONREPORT_VEHICLECLASS']._serialized_end=291
# @@protoc_insertion_point(module_scope)
